<li class="admin-pick">
    <a href="#general">
        <?php echo ___('General'); ?>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#staff">
        <?php echo ___('Staff'); ?>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#staffcategory">
        <?php echo ___('Categories'); ?>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>
