<section id="groupteam" class="admin-section">
    <form method="POST" class="footer-options-form">
        <input type="hidden" name="task" value="general_settings">
        <h2><?php esc_html_e($tournament->name . ' Tournament Teams', 'pixiefreakpanel'); ?></h2>
        <p class="demolink">
            <span class="spliter">|</span>
            <input type="button" class="button button-secondary btn-right" value="<?php ___('Add Team', true); ?>" id="add-group-team">
            <a href="<?php echo route('tournament_index') . '#groups'; ?>">
                <input type="button" class="button button-secondary btn-right" value="<?php ___('Go Back', true); ?>"  style="margin-right: 10px;">
            </a>
        </p>

        <div class="fusion-separator"></div>

        <table id="datatableTournamentGroupTeams" class="widefat fixed" cellspacing="0">
            <thead>
                <tr>
                    <th class="tc"><?php ___('ID', true) ?></th>
                    <th class="tc"><?php ___('Team', true) ?></th>
                    <th class="tc"><?php ___('Win', true) ?></th>
                    <th class="tc"><?php ___('Loss', true) ?></th>
                    <th class="tc"><?php ___('Draw', true) ?></th>
                    <th class="tc"><?php ___('Point', true) ?></th>
                    <th class="tc"><?php ___('Action', true) ?></th>
                </tr>
            </thead>
            <tbody class="sortable">
                <?php if ($tournamentGroupTeams->isNotEmpty()): ?>
                    <?php foreach ($tournamentGroupTeams as $tournamentGroupTeam): ?>

                        <?php include (__DIR__ . '/partials/tournament-group-team-table-tr.phtml'); ?>

                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </form>
</section>

<?php include_once (__DIR__ . '/partials/tournament-group-team-modal.phtml'); ?>

<?php scripts(__DIR__, 'group-teams'); ?>