<div id="modal-team-players" class="modal">
    <div class="modal-content medium">
        <div class="modal-header">
            <span class="close">&times;</span>
            <p class="modal-header-p"><?php echo ___('Edit team players'); ?></p>
        </div>
        <div class="modal-body">
            <div class="staff-member">

                <div class="separator-text">
                    <h4 class="st4"><?php ___('Information', true); ?></h4>
                </div>

                <div class="input-groups">
                    <select class="js-example-basic-multiple input-staff" id="team-players" name="players[]" multiple="multiple">
                        <?php $players = \PixieFreakPanel\Model\Player::query()->get(); ?>
                        <?php if ($players->isNotEmpty()): ?>

                            <?php foreach ($players as $player): ?>

                                <option value="<?php echo $player->id; ?>">
                                    <?php echo ucfirst($player->first_name) .' '. ucfirst($player->last_name); ?>
                                </option>

                            <?php endforeach; ?>

                        <?php endif; ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <input type="submit"
                   name="submitBtn"
                   value="<?php echo ___('SAVE'); ?>"
                   class="button button-primary save-team-players"
                   data-id="0"
            >
        </div>
    </div>
</div>