<div id="modal-player-statistic" class="modal">
    <div class="modal-content medium">
        <div class="modal-header">
            <span class="close">&times;</span>
            <p class="modal-header-p"><?php echo ___('Edit Player Statistic'); ?></p>
        </div>
        <div class="modal-body">
            <table class="form-table">
                <tbody>
                    <tr id="tr-player-stats"></tr>
                </tbody>
            </table>
        </div>
        <div class="modal-footer">
            <input type="submit"
                   name="submitBtn"
                   value="<?php echo ___('SAVE CHANGES'); ?>"
                   class="button button-primary modal-save save-player-statistic"
                   data-id=""
            >
        </div>
    </div>
</div>