<li class="admin-pick">
    <a href="#general">
        <?php echo ___('General'); ?>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#teams">
        <?php echo ___('Teams'); ?>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#players">
        <?php echo ___('Players'); ?>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#achievements">
        <?php echo ___('Achievements'); ?>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>