<section id="general" class="admin-section">
    <form method="POST" class="footer-options-form" action="<?php route('stream_update'); ?>">
        <input type="hidden" name="task" value="general_settings">
        <h2><?php esc_html_e('General Settings', 'pixiefreakpanel'); ?></h2>
        <p class="demolink">
            <span class="spliter">|</span>
            <a target="_blank" href="<?php echo screenshots_path('streams-general.jpg'); ?>">
                <?php esc_html_e('Click here', 'pixiefreakpanel'); ?>
            </a>
            <?php esc_html_e('to see which element you are changing', 'pixiefreakpanel'); ?>
        </p>

        <div class="fusion-separator"></div>

        <table class="form-table">
            <tbody>
                <tr>
                    <th scope="row">
                        <?php esc_html_e('Header Background', 'pixiefreakpanel'); ?>
                        <p class="description">
                            <?php esc_html_e('Here you change/add stream header background.', 'pixiefreakpanel'); ?>
                            <div class="image-preview-holder aboutBG">
                                <img class="image-preview img-preview-bnr" src="<?php echo pixiefreak_settings('stream')->get('banner_image'); ?>">
                            </div>
                        </p>
                    </th>
                    <td class="tdCheckbox">
                        <input type="hidden" name="stream_banner_image" value="" id="banner-image">
                        <input type="button" class="button button-secondary" value="<?php echo ___('SELECT BANNER IMAGE'); ?>" id="select-banner-image">
                    </td>
                </tr>

                <tr>
                    <th scope="row">
		                <?php esc_html_e('Header Title/Subtitle', 'pixiefreakpanel'); ?>
                        <p class="description" style="max-width: 100%;">
			                <?php esc_html_e('Here you can edit/customize header Title/Subtitle text.', 'pixiefreakpanel'); ?>
                        </p>
                    </th>
                    <td class="tdCheckbox">
		                <?php settings_input('stream', 'title', 'text', '', ___('Title')); ?>
		                <?php settings_input('stream', 'subtitle', 'text', '', ___('Subtitle')); ?>
                    </td>
                </tr>

                <tr>
                    <th scope="row">
                        <?php esc_html_e('Stream API', 'pixiefreakpanel'); ?>
                        <p class="description">
                            <?php esc_html_e('Here you can connect to listed streaming API\'s.', 'pixiefreakpanel'); ?>
                        </p>
                    </th>
                </tr>
            </tbody>
        </table>

        <div class="stream-api-box stream-twitch">
            <div class="stream-image">
                <img src="<?php echo plugins_url('pixiefreakpanel/resources/assets/images/twitch.png'); ?>">
            </div>

            <?php
                $twitchConnected  = !empty(pixiefreak_settings('stream')->get('api.twitch'));
                $youtubeConnected = !empty(pixiefreak_settings('stream')->get('api.youtube'));

            ?>
            <div class="stream-button">
                <input type="submit"
                       name="submitBtn"
                       value="<?php echo $twitchConnected ? ___('Connected') : ___('Connect'); ?>"
                       class="button button-stream btn-twitch"
                       data-connected="<?php echo (int) $twitchConnected; ?>"
                       data-type="twitch"
                       data-api="<?php echo pixiefreak_settings('stream')->get('api.twitch'); ?>"
                >
            </div>
        </div>

        <div class="stream-api-box stream-youtube">
            <div class="stream-image">
                <img src="<?php echo plugins_url('pixiefreakpanel/resources/assets/images/youtube.png'); ?>">
            </div>

            <div class="stream-button">
                <input type="submit"
                       name="submitBtn"
                       value="<?php echo $youtubeConnected ? ___('Connected') : ___('Connect') ?>"
                       class="button button-stream btn-youtube"
                       data-connected="<?php echo (int) $youtubeConnected; ?>"
                       data-type="youtube"
                       data-api="<?php echo pixiefreak_settings('stream')->get('api.youtube'); ?>"
                >
            </div>
        </div>

        <?php submit('stream_update'); ?>
    </form>
</section>

<div id="modal-stream-api" class="modal">
    <div class="modal-content medium">
        <div class="modal-header">
            <span class="close">&times;</span>
            <p class="modal-header-p">
                <?php echo ___('Add Api key'); ?>
            </p>
        </div>
        <div class="modal-body">
            <div class="staff-member">
                <div class="input-groups">
                    <div class="separator-text">
                        <h4 class="st4"><?php ___('API KEY', true); ?></h4>
                    </div>
                    <input type="text"
                           class="input-staff"
                           placeholder="<?php ___('API KEY', true); ?>"
                           id="stream-api"
                           data-api=""
                    >
                </div>

            </div>
        </div>
        <div class="modal-footer">
            <input type="submit"
                   name="submitBtn"
                   value="<?php echo ___('SAVE'); ?>"
                   class="button button-primary save-api"
                   data-id="0"
                   data-type=""
            >
        </div>
    </div>
</div>

<?php scripts(__DIR__, 'general'); ?>