<li class="admin-pick">
    <a href="#general">
        General
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#tournaments">
        Tournaments
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#groups">
        Groups
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#groupteam">
        Group Team
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#brackets">
        Brackets
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>