<section id="general" class="admin-section">
    <form method="POST" class="footer-options-form" action="<?php echo route('gallery_update'); ?>">
        <input type="hidden" name="task" value="general_settings">
        <h2><?php esc_html_e('General settings', 'pixiefreakpanel'); ?></h2>
        <p class="demolink">
            <span class="spliter">|</span>
            <a target="_blank" href="<?php echo screenshots_path('gallery-general.jpg'); ?>">
                <?php esc_html_e('Click here', 'pixiefreakpanel'); ?>
            </a>
            <?php esc_html_e('to see which element you are changing', 'pixiefreakpanel'); ?>
        </p>

        <div class="fusion-separator"></div>

        <table class="form-table">
            <tbody>
            <tr>
                <th scope="row">
                    <?php esc_html_e('Banner', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you change/add gallery-page banner.', 'pixiefreakpanel'); ?>
                        <div class="image-preview-holder aboutBG">
                            <img class="image-preview img-preview-bnr" src="<?php echo pixiefreak_settings('gallery')->get('banner_image'); ?>">
                        </div>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <input type="hidden" name="gallery_banner_image" value="" id="banner-image">
                    <input type="button" class="button button-secondary" value="<?php echo ___('SELECT BANNER IMAGE'); ?>" id="select-banner-image">
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <?php esc_html_e('Header Title/Subtitle', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you can edit under-banner Title/Subtitle text.', 'pixiefreakpanel'); ?>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <?php label(___('Title')); ?>
                    <?php settings_input('gallery', 'title'); ?>
                    <?php label(___('Subtitle')); ?>
                    <?php settings_input('gallery', 'subtitle'); ?>
                </td>
            </tr>
            </tbody>
        </table>

        <?php submit('gallery_update'); ?>

    </form>
</section>

<?php scripts(__DIR__, 'general'); ?>