<li class="admin-pick">
    <a href="#header">
        Header
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#slider">
        Slider
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#section">
        Section
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#social">
        Social
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#routes">
        Routes
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#demo">
        Demo
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#footer">
        Footer
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>
