<section id="match" class="admin-section">
    <form method="POST" class="footer-options-form">
        <h2><?php esc_html_e('Matches', 'pixiefreakpanel'); ?></h2>
        <p class="demolink">
            <span class="spliter">|</span>
            <input type="button" class="button button-secondary btn-right" value="<?php ___('Add Match', true); ?>" id="add-match">
        </p>

        <div class="fusion-separator"></div>

        <table id="matchTable" class="widefat fixed" cellspacing="0">
            <thead>
            <tr>
                <th class="tc"><?php ___('ID', true) ?></th>
                <th class="tc"><?php ___('Game', true) ?></th>
                <th class="tc"><?php ___('Team A', true) ?></th>
                <th class="tc"><?php ___('Team B', true) ?></th>
                <th class="tc"><?php ___('Action', true) ?></th>
            </tr>
            </thead>
            <tbody class="sortable">
            <?php if ($matches->isNotEmpty()): ?>

                <?php foreach ($matches as $match): ?>

                    <?php include (__DIR__ . '/partials/match-table-tr.phtml'); ?>

                <?php endforeach; ?>

            <?php endif; ?>
            </tbody>
        </table>
    </form>
</section>

<?php include_once (__DIR__ . '/partials/match-modal.phtml'); ?>

<?php scripts(__DIR__, 'match'); ?>