    <?php $redirectUrlExist = (isset($redirectUrl) && !empty($redirectUrl)); ?>
    <input type="hidden"
           id="redirectUrl"
           name="redirectUrl"
           value="<?php echo $redirectUrlExist ? esc_url($redirectUrl) : '' ?>"
    >
    </main>

    <div class="footer-fo">
        <p class="footer">
            <?php esc_html_e('Crafted with hype by ', 'pixiefreakpanel'); ?>
            <a href="<?php echo esc_url('http://pixiesquad.com') ?>" target="_blank">
                PixieSquad.com
            </a>
    </div>

    <div id="modal-remove-item" class="modal">
        <div class="modal-content small" style="width: 25%">
            <div class="modal-header">
                <span class="close">&times;</span>
                <p class="modal-header-p">
                    <?php echo ___('REMOVE ITEM'); ?>
                </p>
            </div>
            <div class="modal-body">
                <div class="staff-member">
                    <h4 class="st4" style="
                        text-align: center;
                        font-size: 13px;
                        margin-bottom: -10px !important;
                    ">Are you sure you want to remove this item ?</h4>
                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" name="submitBtn" value="DELETE" class="button button-primary confirm-remove-btn" style="
                    background: #dc3232;
                    border-color: #dc3232;
                    box-shadow: inset 0 2px 0 #dc3232;
                    text-shadow: none !important;
                ">
            </div>
        </div>
    </div>

    <div id="modal-copied" class="modal">
        <div class="modal-content small" style="width: 25%">
            <div class="modal-body">
                <div class="staff-member">
                    <h4 class="st4" style="
                        text-align: center;
                        font-size: 13px;
                    ">Successfully copied tag to clipboard!</h4>
                </div>
            </div>
        </div>
    </div>
</div>

<?php include_once (__DIR__ .'/scripts.phtml'); ?>