<section id="general" class="admin-section">
    <form method="POST" class="footer-options-form" action="<?php route('sponsor_update'); ?>">
        <input type="hidden" name="task" value="general_settings">
        <h2><?php esc_html_e('General settings', 'pixiefreakpanel'); ?></h2>
        <p class="demolink">
            <span class="spliter">|</span>
            <a target="_blank" href="<?php echo screenshots_path('sponsors-general.jpg'); ?>">
                <?php esc_html_e('Click here', 'pixiefreakpanel'); ?>
            </a>
            <?php esc_html_e('to see which element you are changing', 'pixiefreakpanel'); ?>
        </p>

        <div class="fusion-separator"></div>

        <table class="form-table">
            <tbody>
            <tr>
                <th scope="row">
                    <?php esc_html_e('Header Background', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you change/add sponsor header background.', 'pixiefreakpanel'); ?>
                        <div class="image-preview-holder aboutBG">
                            <img class="image-preview img-preview-bnr" src="<?php echo pixiefreak_settings('sponsor')->get('banner_image'); ?>">
                        </div>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <input type="hidden" name="sponsor_banner_image" value="" id="banner-image">
                    <input type="button" class="button button-secondary" value="<?php echo ___('SELECT BANNER IMAGE'); ?>" id="select-banner-image">
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <?php esc_html_e('Header Title/Subtitle', 'pixiefreakpanel'); ?>
                    <p class="description" style="max-width: 100%;">
                        <?php esc_html_e('Here you can edit/customize header Title/Subtitle text.', 'pixiefreakpanel'); ?>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <?php settings_input('sponsor', 'title', 'text', '', ___('Title')); ?>
                    <?php settings_input('sponsor', 'subtitle', 'text', '', ___('Subtitle')); ?>
                    <?php esc_html_e('Show Title', 'pixiefreakpanel'); ?>
                    <?php settings_checkbox('sponsor', 'show_title'); ?>
                        <br/>
                    <?php esc_html_e('Show Subtitle', 'pixiefreakpanel'); ?>
                    <?php settings_checkbox('sponsor', 'show_subtitle'); ?>
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <?php esc_html_e('CTA Button', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you can customize header CTA button.', 'pixiefreakpanel'); ?>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <?php settings_input('sponsor', 'cta.text', 'text', '', ___('CTA Text')); ?>
                    <?php settings_input('sponsor', 'cta.link', 'text', '', ___('CTA Link')); ?>
                    <?php settings_checkbox('sponsor', 'cta.show', ['SHOW', 'HIDE']); ?>
                </td>
            </tr>
            </tbody>
        </table>

        <?php submit('sponsor_update'); ?>

    </form>
</section>

<?php scripts(__DIR__, 'general'); ?>