<section id="sponsors" class="admin-section">
    <form method="POST" class="footer-options-form" action="<?php route('sponsor_update'); ?>">
        <h2><?php esc_html_e('Sponsors list', 'pixiefreakpanel'); ?></h2>
        <p class="demolink">
            <span class="spliter">|</span>
            <input type="button" class="button button-secondary btn-right" value="<?php ___('Add Sponsor', true); ?>" id="add-sponsor">
        </p>

        <div class="fusion-separator"></div>

        <table id="datatableSponsor" class="widefat fixed" cellspacing="0">
            <thead>
            <tr>
                <th class="tc"  style="width: 5%"><?php ___('#', true) ?></th>
                <th class="tc"><?php ___('ID', true) ?></th>
                <th class="tc"><?php ___('Name', true) ?></th>
                <th class="tc"><?php ___('Logo', true) ?></th>
                <!--<th class="tc"><?php /*___('Url', true) */?></th>-->
                <th class="tc"><?php ___('Social', true) ?></th>
                <th class="tc"><?php ___('Type', true) ?></th>
                <th class="tc"><?php ___('Action', true) ?></th>
            </tr>
            </thead>
            <tbody class="sortable">
            <?php if ($sponsors->isNotEmpty()): ?>

                <?php foreach ($sponsors as $sponsor): ?>

                    <?php include (__DIR__ . '/partials/sponsor-table-tr.phtml'); ?>

                <?php endforeach; ?>

            <?php endif; ?>
            </tbody>
        </table>
    </form>
</section>

<div id="modal-sponsor" class="modal">
    <div class="modal-content medium">
        <div class="modal-header">
            <span class="close">&times;</span>
            <p class="modal-header-p">
                <?php echo ___('Create Sponsor'); ?>
            </p>
        </div>
        <div class="modal-body">
            <div class="staff-member">
                <div class="separator-text">
                    <h4 class="st4"><?php ___('Logo', true); ?></h4>
                </div>

                <div class="staff-member-image">
                    <img src="">
                    <input type="hidden" value="" id="sponsor-logo">
                    <input type="submit" name="submitBtn"
                           value="<?php echo ___('Choose image'); ?>"
                           class="button button-primary save-stats new-image"
                    >
                </div>

                <div class="separator-text">
                    <h4 class="st4"><?php ___('Information', true); ?></h4>
                </div>

                <div class="input-groups">
                    <input type="text" class="input-staff" placeholder="<?php ___('Sponsor Name', true); ?>" id="sponsor-name">
                    <input type="text" class="input-staff" placeholder="<?php ___('Url', true); ?>" id="sponsor-url">
                    <textarea class="input-staff" id="sponsor-about" title="<?php ___('Sponsor About Information'); ?>"
                        placeholder="<?php ___('About', true); ?>"></textarea>

                    <select class="staff-select input-staff" id="sponsor-type" title="<?php ___('Select Type', true); ?>">
                        <option value="1" selected=""><?php ___('Default', true); ?></option>
                        <option value="2"><?php ___('Head Sponsor', true); ?></option>
                    </select>

                    <div class="separator-text">
                        <h4 class="st4"><?php ___('Socials', true); ?></h4>
                    </div>

                    <input type="text" class="input-staff" placeholder="<?php ___('Facebook', true); ?>" id="sponsor-facebook">
                    <input type="text" class="input-staff" placeholder="<?php ___('Twitter', true); ?>" id="sponsor-twitter">
                    <input type="text" class="input-staff" placeholder="<?php ___('Instagram', true); ?>" id="sponsor-instagram">
                    <input type="text" class="input-staff" placeholder="<?php ___('Twitch', true); ?>" id="sponsor-twitch">
                    <input type="text" class="input-staff" placeholder="<?php ___('Steam', true); ?>" id="sponsor-steam">
                </div>

            </div>
        </div>
        <div class="modal-footer">
            <input type="submit" name="submitBtn" value="<?php echo ___('SAVE'); ?>"
                   class="button button-primary save-sponsor" data-id="0">
        </div>
    </div>
</div>

<?php scripts(__DIR__, 'sponsors'); ?>