<section id="achievements" class="admin-section">
    <form method="POST" class="footer-options-form">
        <h2><?php esc_html_e('Achievements', 'pixiefreakpanel'); ?></h2>
        <p class="demolink">
            <span class="spliter">|</span>
            <input type="button" class="button button-secondary btn-right" value="<?php ___('Add Achievement', true); ?>" id="add-achievement">
        </p>

        <div class="fusion-separator"></div>

        <table id="datatableAchievements" class="widefat fixed" cellspacing="0">
            <thead>
            <tr>
                <th class="tc"><?php ___('ID', true) ?></th>
                <th class="tc"><?php ___('Name', true) ?></th>
                <th class="tc"><?php ___('Thumbnail', true) ?></th>
                <th class="tc"><?php ___('Action', true) ?></th>
            </tr>
            </thead>
            <tbody class="sortable sortableAchievement">
            <?php if ($achievements->isNotEmpty()): ?>

                <?php foreach ($achievements as $achievement): ?>

                    <?php include (__DIR__ . '/partials/team-achievement-table-tr.phtml'); ?>

                <?php endforeach; ?>

            <?php endif; ?>
            </tbody>
        </table>

        <?php include_once (__DIR__ . '/partials/team-achievement-modal.phtml'); ?>
    </form>
</section>

<?php scripts(__DIR__, 'achievements'); ?>