<section id="gear" class="admin-section">
    <form method="POST" class="footer-options-form">
        <input type="hidden" name="task" value="general_settings">
        <h2><?php esc_html_e('Gear Information', 'pixiefreakpanel'); ?></h2>
        <p class="demolink">
            <span class="spliter">|</span>
            <input type="button" class="button button-secondary btn-right" value="<?php ___('Add Gear Item', true); ?>" id="add-gear">
        </p>

        <div class="fusion-separator"></div>

        <table id="datatableGear" class="widefat fixed" cellspacing="0">
            <thead>
            <tr>
                <th class="tc"><?php ___('ID', true) ?></th>
                <th class="tc"><?php ___('Name', true) ?></th>
                <th class="tc"><?php ___('Type', true) ?></th>
                <th class="tc"><?php ___('Image', true) ?></th>
                <!--<th class="tc"><?php /*___('Url', true) */?></th>-->
                <th class="tc"><?php ___('Link', true) ?></th>
                <th class="tc"><?php ___('New', true) ?></th>
                <th class="tc"><?php ___('Action', true) ?></th>
            </tr>
            </thead>
            <tbody class="sortable sortableGear">
            <?php if ($gears->isNotEmpty()): ?>

                <?php foreach ($gears as $gear): ?>

                    <?php include (__DIR__ . '/partials/gear-table-tr.phtml'); ?>

                <?php endforeach; ?>

            <?php endif; ?>
            </tbody>
        </table>
    </form>
</section>

<div id="modal-gear" class="modal">
    <div class="modal-content medium">
        <div class="modal-header">
            <span class="close">&times;</span>
            <p class="modal-header-p">
                <?php echo ___('Create Gear'); ?>
            </p>
        </div>
        <div class="modal-body">
            <div class="staff-member">
                <div class="separator-text">
                    <h4 class="st4"><?php ___('Image', true); ?></h4>
                </div>

                <div class="staff-member-image">
                    <img src="">
                    <input type="hidden" value="" id="gear-image">
                    <input type="submit" name="submitBtn"
                           value="<?php echo ___('Choose image'); ?>"
                           class="button button-primary save-stats new-image"
                    >
                </div>

                <div class="separator-text">
                    <h4 class="st4"><?php ___('Information', true); ?></h4>
                </div>

                <div class="input-groups">
                    <input type="text" class="input-staff" placeholder="<?php ___('Gear Name', true); ?>" id="gear-name">
                    <input type="text" class="input-staff" placeholder="<?php ___('Link', true); ?>" id="gear-link">

                    <select class="staff-select input-staff" id="gear-type" title="<?php ___('Select Gear Type', true); ?>">
                        <?php $i=0; foreach (\PixieFreakPanel\Model\Gear::TYPES as $key => $type): $i++;?>
                            <option value="<?php echo $key; ?>" <?php echo $i === 1 ? 'selected="selected"' : ''; ?>><?php echo $type; ?></option>
                        <?php endforeach; ?>
                    </select>

                    <select class="staff-select input-staff" id="gear-recommended" title="<?php ___('Is New', true); ?>">
                        <option value="1" selected=""><?php ___('Yes', true); ?></option>
                        <option value="2" selected=""><?php ___('No', true); ?></option>
                    </select>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <input type="submit"
                   name="submitBtn"
                   value="<?php echo ___('SAVE'); ?>"
                   class="button button-primary save-gear"
                   data-id="0">
        </div>
    </div>
</div>

<?php scripts(__DIR__, 'gear'); ?>