<section id="general" class="admin-section">
    <form method="POST" class="footer-options-form" action="<?php route('about_update'); ?>">
        <input type="hidden" name="task" value="general_settings">

        <h2><?php esc_html_e('General settings', 'pixiefreakpanel'); ?></h2>
        <p class="demolink">
            <span class="spliter">|</span>
            <a target="_blank" href="<?php echo screenshots_path('about-general.jpg'); ?>">
                <?php esc_html_e('Click here', 'pixiefreakpanel'); ?>
            </a>
            <?php esc_html_e('to see which element you are changing', 'pixiefreakpanel'); ?>
        </p>

        <div id="modal-stats" class="modal">
            <div class="modal-content medium">
                <div class="modal-header">
                    <span class="close">&times;</span>
                    <p class="modal-header-p"><?php echo ___('Edit stats Icon'); ?></p>
                </div>
                <div class="modal-body">
                    <table class="form-table">
                        <tbody>
                        <tr>
                            <td class="tdCheckbox">
                                <?php foreach (json_decode($about->stats, true) as $key => $statistic): ?>
                                    <div class="input-group">
                                        <div class="modal-input stat-pr" data-id="<?php echo $key; ?>">
                                            <div class="image-preview-holder aboutBG stats-modal-preview<?php echo $key; ?> stats-modal-preview" style="display: none;">
                                                <img class="image-preview img-preview-bnr"
                                                     src="<?php echo $statistic['icon']; ?>"
                                                >
                                            </div>
                                            <input type="hidden" name="stats[]" value="<?php echo $statistic['icon']; ?>" id="icon-<?php echo $key; ?>" class="stats-input">
                                            <input type="submit" value="<?php echo ___('Change Icon'); ?>"
                                                   class="button button-primary modal-stats-btn stats-icon"
                                                   data-id="<?php echo $key; ?>"
                                                   style="<?php echo $statistic['icon'] ? 'background-image: url(\''.$statistic['icon'].'\') !important;' : ''; ?>"
                                            >
                                        </div>

                                        <div class="modal-input">
                                            <?php input('text', 'stats[]', $statistic['title'], 'stats-input', ___('Title')); ?>
                                        </div>

                                        <div class="modal-input">
                                            <?php input('text', 'stats[]', $statistic['label'], 'stats-input', ___('Label')); ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <input type="submit" name="submitBtn" value="<?php echo ___('SAVE CHANGES'); ?>" class="button button-primary save-stats">
                </div>
            </div>
        </div>

        <table class="form-table">
            <tbody>
            <tr>
                <th scope="row">
                    <?php esc_html_e('Cover', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you change/add about-page cover.', 'pixiefreakpanel'); ?>
                        <div class="image-preview-holder aboutBG aboutCover">
                            <img class="image-preview img-preview-bnr" <?php echo !empty($about->cover) ? 'src="'.$about->cover.'"' : ''; ?>>
                        </div>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <input type="hidden" name="cover" value="" id="cover-image">
                    <input type="button" class="button button-secondary" value="<?php echo ___('SELECT COVER IMAGE'); ?>" id="select-cover-image">
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <?php esc_html_e('Banner', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you change/add about-page banner.', 'pixiefreakpanel'); ?>
                        <div class="image-preview-holder aboutBG aboutBanner">
                            <img class="image-preview img-preview-bnr" <?php echo !empty($about->banner) ? 'src="'.$about->banner.'"' : ''; ?>>
                        </div>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <input type="hidden" name="banner" value="" id="banner-image">
                    <input type="button" class="button button-secondary" value="<?php echo ___('SELECT BANNER IMAGE'); ?>" id="select-banner-image">
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <?php esc_html_e('Description', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you can change/add about text.', 'pixiefreakpanel'); ?>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <?php textarea(!empty($about->description) ? $about->description : '', 'description'); ?>
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <?php esc_html_e('Statistic Icons', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you can description-right statistic information.', 'pixiefreakpanel'); ?>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <input type="button" class="button button-secondary" value="<?php echo ___('UPDATE STATISTIC INFORMATION'); ?>" id="modal-stats-btn">
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <?php esc_html_e('Who we are Text', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you can edit under-banner "Who we are" text.', 'pixiefreakpanel'); ?>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <?php label(___('Text')); ?>
                    <?php settings_input('about', 'who_we_are'); ?>
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <?php esc_html_e('Some more Text', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you can edit under-banner "Some more information about us" text.', 'pixiefreakpanel'); ?>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <?php label(___('Text')); ?>
                    <?php settings_input('about', 'some_more'); ?>
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <?php esc_html_e('CTA Button-Left', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you can edit CTA Left Button information positioned under slider.', 'pixiefreakpanel'); ?>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <?php label(___('Text')); ?>
                    <?php settings_input('about', 'media_kit.text'); ?>

                    <?php label(___('Link/Url')); ?>
                    <?php settings_input('about', 'media_kit.link'); ?>

                    <?php settings_checkbox('about', 'media_kit.show', [___('SHOW'), ___('HIDE')]); ?>
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <?php esc_html_e('CTA Button-Right', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you can edit CTA Right Button information positioned under slider.', 'pixiefreakpanel'); ?>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <?php label(___('Text')); ?>
                    <?php settings_input('about', 'all_teams.text'); ?>

                    <?php label(___('Link/Url')); ?>
                    <?php settings_input('about', 'all_teams.link'); ?>

                    <?php settings_checkbox('about', 'all_teams.show', [___('SHOW'), ___('HIDE')]); ?>
                </td>
            </tr>

            <tr>
                <th scope="row">
                    <?php esc_html_e('Footer Information', 'pixiefreakpanel'); ?>
                    <p class="description">
                        <?php esc_html_e('Here you can about footer information.', 'pixiefreakpanel'); ?>
                    </p>
                </th>
                <td class="tdCheckbox">
                    <?php label(___('Info First')); ?>
                    <?php settings_input('about', 'about_first.icon'); ?>
                    <?php settings_input('about', 'about_first.title'); ?>
                    <?php settings_input('about', 'about_first.subtitle'); ?>
                    <?php settings_checkbox('about', 'about_first.show', [___('SHOW'), ___('HIDE')]); ?>

                    <hr/>
                    <?php label(___('Info Second')); ?>
                    <?php settings_input('about', 'about_second.icon'); ?>
                    <?php settings_input('about', 'about_second.title'); ?>
                    <?php settings_input('about', 'about_second.subtitle'); ?>
                    <?php settings_checkbox('about', 'about_second.show', [___('SHOW'), ___('HIDE')]); ?>

                    <hr/>
                    <?php label(___('Info Third')); ?>
                    <?php settings_input('about', 'about_third.icon'); ?>
                    <?php settings_input('about', 'about_third.title'); ?>
                    <?php settings_input('about', 'about_third.subtitle'); ?>
                    <?php settings_checkbox('about', 'about_third.show', [___('SHOW'), ___('HIDE')]); ?>

                    <hr/>
                    <?php label(___('Info Fourth')); ?>
                    <?php settings_input('about', 'about_fourth.icon'); ?>
                    <?php settings_input('about', 'about_fourth.title'); ?>
                    <?php settings_input('about', 'about_fourth.subtitle'); ?>
                    <?php settings_checkbox('about', 'about_fourth.show', [___('SHOW'), ___('HIDE')]); ?>
                </td>
            </tr>
            </tbody>
        </table>

        <?php submit('about_update'); ?>

    </form>
</section>

<?php scripts(__DIR__ , 'general'); ?>