<li class="admin-pick">
    <a href="#general">
        <?php echo ___('General'); ?>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#photo">
        <?php echo ___('Photos'); ?>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>

<li class="admin-pick">
    <a href="#category">
        <?php echo ___('Categories'); ?>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</li>